# Generated by Django 3.1.7 on 2021-03-31 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_order_product_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_who_ordered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.customer'),
        ),
    ]
